dist: trusty
language: c
compiler: gcc
env:
  global:
    - MY_PV=0.2.10
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y check cmake libc6-dbg rpm
  - wget https://launchpad.net/ubuntu/+source/valgrind/1:3.13.0-1ubuntu3/+build/13618072/+files/valgrind_3.13.0-1ubuntu3_amd64.deb
  - sudo dpkg -i *.deb
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
