dist: trusty
sudo: false
language: c

addons:
 apt:
     sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-6
      - clang-5.0
      - check-0.12.0
script:
 - mkdir build
 - cd build
 - cmake ..
 - make
